on:
  push:
    branches:
    - main

jobs:
  my_job:
    strategy:
      matrix:
        node-version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    name: deploy to
    runs-on: ${{ matrix.os }}
    steps:
    - run: echo ${{ matrix.node-version}}
    - run: echo ${{ matrix.os }}
    - uses: ./.github/workflows/actions/reusable-matrix.yaml
